platforms:
  - name: ubuntu-22.04
    groups:
      - vault_instances
    image: dokken/ubuntu-22.04
    pre_build_image: true
    command: /lib/systemd/systemd
    privileged: true
    cgroup_parent: docker.slice
