- name: Installing HashiCorp Vault
  ansible.builtin.unarchive:
    remote_src: true
    src: "https://releases.hashicorp.com/vault/{{ vault_version | string }}/vault_{{ vault_version | string }}_linux_amd64.zip"
    dest: "{{ vault_bin_dir }}/"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0770
  become: true

- name: Set cap_ipc_lock=+ep capability on vault's binary
  community.general.capabilities:
    path: "{{ vault_bin_dir }}/vault"
    capability: cap_ipc_lock=+ep
    state: present
  become: true
  changed_when: false
  notify:
    - Restart vault
