- name: Pre flight checks
  ansible.builtin.include_tasks: pre-flight.yml

- name: Setup user
  ansible.builtin.include_tasks: user.yml

- name: Install Vault
  ansible.builtin.include_tasks: install.yml

- name: Configure vault
  ansible.builtin.include_tasks: config.yml

- name: Install Vault service
  ansible.builtin.include_tasks: service.yml
