- name: Ensure that vault_config_template is defined
  ansible.builtin.assert:
    that:
      - vault_config_template
    fail_msg: "'vault_config_template' must be defined"

- name: Updating Apt Cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Installing dependencies
  ansible.builtin.apt:
    name:
      - unzip
    state: present
  become: true
  register: result
  until: result is successful
