- name: Defining _vault_exec_output
  set_fact:
    _vault_exec_output: ">> {{ vault_log_dir }}/vault.log 2>&1"
  when: vault_log_dir

- name: Configuring vault service
  template:
    src: etc/systemd/system/vault.service.j2
    dest: /etc/systemd/system/vault.service
    owner: root
    group: root
    mode: 0664
  become: true
  notify:
    - reload systemd
    - restart vault

- name: Ensuring vault service is enabled
  service:
    name: vault
    enabled: true
  become: true
