- name: Reload systemd
  ansible.builtin.systemd:
    name: vault
    daemon_reload: true
  become: true

- name: Restart vault
  ansible.builtin.service:
    name: vault
    state: restarted
  become: true
