- name: Prepare
  hosts: all
  connection: local

  tasks:
    - name: Update Apt Cache
      ansible.builtin.apt:
        update_cache: true
      become: true

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - python3-dev
          - python3-pip
          - python3-setuptools
          - python3-venv
          - virtualenv
      become: true
      register: result
      until: result is successful
