name: Molecule Test

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.gitignore'
      - '**.md'
      - 'meta/main.yml'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - '**.md'
      - 'meta/main.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        scenario:
          - debian-9
          - debian-10
          - ubuntu-18.04
          - ubuntu-20.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pip-tools
          pip-sync requirements.txt
          ansible --version
          molecule --version
      - name: Molecule
        run: |
          molecule --base-config molecule/_shared/base.yml test --scenario-name ${{ matrix.scenario }}
